version: "2"
services:

  consul:
    image: consul
    ports:
      - "8500:8500"

  roasts:
    image: roasts
    build:
      context: ./roasts
    ports:
      - 3000:80

  brews:
    image: brews
    build:
      context: ./brews
    ports:
      - 3001:80

  menu:
    image: menu
    build:
      context: ./menu
    environment:
      - KV_ROOT=http://consul:8500/v1/kv
    ports:
      - 3002:80
    links:
      - brews:brews
      - roasts:roasts
      - consul:consul
